services:
  - type: web
    name: dr-ai
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    envVars:
      - key: OPENROUTER_KEY
        sync: false          # la cargas manualmente en Render
